name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  centos-8:
    dependencies:
      - curl
      - which
      - epel-release
      - imlib2
      - newt
      - shared-mime-info
    build_dependencies:
      - https://download.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/i/imlib2-1.4.9-8.el8.x86_64.rpm
      - https://download.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/i/imlib2-devel-1.4.9-8.el8.x86_64.rpm
      - shared-mime-info
  debian-11:
    dependencies:
      - curl
      - gnupg2
      - libimlib2
      - shared-mime-info
      - whiptail
    build_dependencies:
      - libimlib2
      - libimlib2-dev
      - shared-mime-info
  debian-12:
    dependencies:
      - curl
      - libimlib2
      - shared-mime-info
      - whiptail
    build_dependencies:
      - libimlib2
      - libimlib2-dev
      - shared-mime-info
  ubuntu-18.04:
    dependencies:
      - curl
      - gnupg2
      - libimlib2
      - shared-mime-info
      - whiptail
    build_dependencies:
      - libimlib2
      - libimlib2-dev
      - shared-mime-info
  ubuntu-20.04:
    dependencies:
      - curl
      - gnupg2
      - libimlib2
      - shared-mime-info
      - whiptail
    build_dependencies:
      - libimlib2
      - libimlib2-dev
      - shared-mime-info
  ubuntu-22.04:
    dependencies:
      - curl
      - gnupg2
      - libimlib2
      - shared-mime-info
      - whiptail
    build_dependencies:
      - libimlib2
      - libimlib2-dev
      - shared-mime-info
  sles-15:
    dependencies:
      - curl
      - libImlib2-1
      - imlib2
      - newt
      - shared-mime-info
    build_dependencies:
      # Add packages required for build that are not in the official SLES repo.
      # Direct URLs must be used since we cannot add repos on packager.io
      #   (would require a paid SLES account and credential management on packager.io).
      - https://ftp.lysator.liu.se/pub/opensuse/ports/aarch64/distribution/leap/15.4/repo/oss/x86_64/imlib2-1.4.10-1.28.x86_64.rpm
      - https://ftp.lysator.liu.se/pub/opensuse/ports/aarch64/distribution/leap/15.4/repo/oss/x86_64/imlib2-devel-1.4.10-1.28.x86_64.rpm
      - https://ftp.lysator.liu.se/pub/opensuse/ports/aarch64/distribution/leap/15.4/repo/oss/x86_64/imlib2-filters-1.4.10-1.28.x86_64.rpm
      - https://ftp.lysator.liu.se/pub/opensuse/ports/aarch64/distribution/leap/15.4/repo/oss/x86_64/libImlib2-1-1.4.10-1.28.x86_64.rpm
      - shared-mime-info
      - libmariadb-devel
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres:15
  - redis
before_install: contrib/packager.io/preinstall.sh
